### PR TITLE
Fix Git Push policies. Remove `ignore` block from the Git Push policies 

### PR DESCRIPTION
**Pull request by aknysh**
## what
* Fix Git push policies
* Remove `ignore` block from the Git Push policies 

## why
* We already provide `propose` and `track` block which have all the required logic to evaluate if a proposed a tracked run needs to be started
* The `ignore` block is redundant in the policies, since it uses the same (but opposite) logic as the `propose` and `track `block
* Having the `ignore` block in the two Git Push policies prevents a run from being triggered in some cases (e.g. when pushing directly to the default/tracked branch, the `ignore` block in the `git_push.propose-run.rego` policy prevents the traked run from being triggered in the `git_push.tracked-run.rego` policy

```
The policy may define boolean track, propose and ignore rules. 
The positive outcome of at least one ignore rule causes the push to be ignored, 
no matter the outcome of other rules. 
The positive outcome of at least one track rule triggers a tracked run. 
The positive outcome of at least one propose rule triggers a proposed run.
```

## references
* https://docs.spacelift.io/concepts/policy/git-push-policy

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@aknysh I believe I just hit this -- upgraded to 0.33 just a moment ago and ran into a push that didn't cause a trigger like i'd expect. Mind if I merge?

**Comment by aknysh** [comment]
> @aknysh I believe I just hit this -- upgraded to 0.33 just a moment ago and ran into a push that didn't cause a trigger like i'd expect. Mind if I merge?

@Gowiem  it worked Ok when you merge a PR into the default/tracked branch.
It just did not work when you push (or a bot pushes) directly to the default/tracked branch (e.g. from GitHub UI)

**Comment by Gowiem** [comment]
@aknysh yeah, funnily enough I hit that right off. Project I'm working on is just myself, so I pushed a change directly to the `main` branch and it didn't trigger. Then I realized you're PR. Well done on the timing. Will test this out now.

**Comment by aknysh** [comment]
@Gowiem  I just tested it, all OK :)

**Comment by Gowiem** [comment]
@aknysh Same here 👍 👍

**Pull request merged**
