### PR TITLE
Add stack_name_prefix

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Add stack_name_prefix

## why
* Admin stacks can specify a prefix for all child stacks

## references
* N/A

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]
This seems fine to me. Get it updated to latest code and let's get it merged 👍

**Comment by Gowiem** [comment]
@nitrocode friendly ping! You still need this?

**Comment by nitrocode** [comment]
Hi Matt. It's been a long time and I did not do the best job of describing the use case. It's possible that this was client related which is why there aren't any direct links. Someone who still has access to the customers (if they are still engaged) will be able to see the private links.

It's probably safe to close for now.

**Pull request closed without merging**
