### PR TITLE
feat: adds some simple tests to showcase how easy rego testing is

### PR DESCRIPTION
**Pull request by Gowiem**
## what
* Adds a few rego policy tests via `_test.rego` files
	* Here are the results of these tests: CleanShot 2021-06-23 at 15 24 37

## why
* To showcase how easy this can be after discussing with @osterman during #office-hours

## references
* N/A

### CODE REVIEW

**Comment by Gowiem** [comment]
@osterman let me know if you'd like me to wire up a GH action for this. I'd be happy to do so in some off time.

**Comment by Gowiem** [comment]
@osterman @aknysh policy tests have been added. Let me know your thoughts 👍

**Review by aknysh — APPROVED** [review]
thanks @Gowiem

**Pull request merged**
